name: Run News Scraper

on:
  schedule:
    - cron: '0 * * * *'  # รันทุกชั่วโมง (นาทีที่ 0)
  workflow_dispatch:     #允许手动กดรันทดสอบ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: python main.py
